### ISSUE TITLE
Question: Need book recommendation, how to host nServiceBus on Azure web app

### ISSUE THREAD

**Issue by artsai** [DavidBoike/feedback#1]
Hi David, 
Which one of your book describe how to host on Azure? 
http://docs.particular.net/nservicebus/azure/hosting page doesn't describe much about Azure Website model. Is it not recommended method?  the link stated "The only quirk in this model is that Azure website is built with cheap hosting in mind. "  But it is true today? 
http://azure.microsoft.com/en-us/pricing/details/app-service/

Thank you for your time,
Art

**Comment by DavidBoike** [comment]
Hi @artsai,

I'm really sorry. Somehow I got unsubscribed from this repository months ago and didn't see your question. Did you ever find a decent answer?

AFAIK, hosting NServiceBus in an Azure Website wouldn't really be any different than self hosting in an IIS website on premise, except it could be shut down at any time from inactivity. You wouldn't want to host reliable handlers this way. They might not be awake to process messages. But actions on the website could certainly send messages to Azure Storage Queues or Azure Service Bus for other endpoints to consume.
