### ISSUE TITLE
The meetup tonight - my meeting rating/polling/chat app....

### ISSUE THREAD

**Issue by doug62** [DavidBoike/feedback#2]
Hey David - I'm looking forward to this evening.  I have an app that lets you rate office meetings (too long/waste/quality).  One feature is real-time polling - so for example you could engage folks at seminars and see the results move on the screen, or ask "How interested are you in purchasing in the next 6 months", another feature is a categorized/tree chat feature so folks could send you questions while presenting....  It also adds the participants to your contacts (sales/networking)....

Outlook / Google plug in - also works as a phone app.

Hoping for a minute of your time at the shindig to get your feedback/thoughts...

Doug

**Comment by DavidBoike** [comment]
Ugh, somehow I got myself unsubscribed from my own repository and missed this. Sorry! Did we talk that night?
