### ISSUE TITLE
Permission to reference your book

### ISSUE THREAD

**Issue by cpear** [DavidBoike/feedback#3]
Hi Mr. Boike. I am going to be giving a talk at MeasureUp in Austin at the end of the month titled Distributed Systems 101. I was hoping to get permission to use your book as a reference when I speak on the Fallacies of Distributed Computing.

I don't plan on using anything verbatim but I wanted to make sure my bases were covered in case I did use something inadvertently. I plan to just use the book as a base reference when putting my slides together. I am also going to be dropping in a few plugs for the book (and you as well).

I am also going to do a few slides on NServiceBus too.

Thanks,
Colin Pear

**Comment by DavidBoike** [comment]
Hi @cpear!

Are you referring to the Dr. Harvey book? Please be my guest! All of us at Particular would like that sort of knowledge disseminated far and wide.

We give that book away as an ebook offer. Would you like a link to the landing page for it?

**Comment by cpear** [comment]
Yes thats the book. Definetly! Send me the link for the eBook.

Thanks so much.

Colin

Get Outlook for Android

On Fri, Jul 1, 2016 at 8:55 PM -0500, "David Boike" notifications@github.com wrote:

Hi @cpear!

Are you referring to the Dr. Harvey book? Please be my guest! All of us at Particular would like that sort of knowledge disseminated far and wide.

We give that book away as an ebook offer. Would you like a link to the landing page for it?

---

**Comment by DavidBoike** [comment]
By "end of month" I presume you mean end of July, so hopefully you can wait until I'm back in the office on Thursday? Will definitely send you a link.

**Comment by cpear** [comment]
Yeah. July 23 at MeasureUp. So no rush.

Colin

Date: Fri, 1 Jul 2016 19:05:16 -0700

**Comment by DavidBoike** [comment]
@cpear Here you go: http://go.particular.net/MUBook

Good luck!
