### ISSUE TITLE
Use NServiceBus tutorials?

### ISSUE THREAD

**Issue by mikedevbo** [DavidBoike/feedback#5]
Hi David,

I write a little bit about software development especially around NServiceBus and Particular Service Platform on my blog ddtd.pl (Polish language).
I have an idea to mix learning F# language with NServiceBus use cases. I want to write couple articles with this topic.

Could I use use cases and examples from tutorials?
- https://docs.particular.net/tutorials/nservicebus-step-by-step/
- https://docs.particular.net/tutorials/nservicebus-sagas/1-getting-started/ ?

I'll re-route links to these tutorials and write that whole idea based on them. Potential reader will be able to open tutorials and read more about NServiceBus.

Regards
Michał

**Comment by DavidBoike** [comment]
I see no problem with that. Go ahead and spread the word!

Also note the footer of our documentation site which states:

> Sample and snippet code under [MIT License](https://opensource.org/licenses/MIT)

Which gives you permission to use/reuse/remix the code pretty much however you want.

When you publish, let me know and I'll make sure we tweet about it from the ParticularSW account.

**Comment by mikedevbo** [comment]
Thanks a lot!

**Comment by DavidBoike** [comment]
Although, one thing that would be really helpful to me personally - the HTML of your blog currently outputs `<html lang="en">` which makes my browser think it's in English. If it were `<html lang="pl">` then Google would probably offer to translate it to English and I could (at least try to) read your stuff!

**Comment by mikedevbo** [comment]
Thanks for the advice. I set lang to "pl"
Happy reading :)

By the way I'll have my first public speaking on Polish conference https://4developers.org.pl/wroclaw/
I'll talk about how to use NServiceBus in systems integration - https://4developers.org.pl/lecture_wroclaw_2019/#id=56139

**Comment by mikedevbo** [comment]
following your advice I let you know that just blogged second part of the series https://ddtd.pl/2019/09/16/fsharp-nservicebus-practical-guide-endpoint-configuration.html

**Comment by mikedevbo** [comment]
Hi David,

Quick update

- I wrote 4 out of 6 articles have to write Retail E-commerce System using F# language. The last you can find at https://ddtd.pl/2019/10/13/fsharp-nservicebus-practical-guide-multiple-endpoints.html

- I’m after my first conference public speech. You can find slides and demo at https://github.com/mikedevbo/system-integration-messaging-queueing-nservicebus-presentation.
I showed demo using MSMQTransport but I discovered https://www.nuget.org/packages/Particular.PlatformSample It’s very very very cool feature :) Now it’s possbile to show ServicePulse functionality using LearningTransport and highlight the NServiceBus possibilities of using many queue transports

**Comment by DavidBoike** [comment]
Awesome!
