### ISSUE TITLE
Using a SmartThings sensor in "garage door" mode with Home Assistant

### ISSUE THREAD

**Issue by jsturtevant1078** [DavidBoike/feedback#7]
Well, my faith in the web just went up 1000%
I'm completing my migration from Smartthings to Home Assistant and [this article on David's blog](https://www.davidboike.dev/2020/12/smartthings-sensor-garage-door-mode-with-home-assistant/?utm_source=pocket_mylist) was perfect and well written.
Many thanks David

**Comment by DavidBoike** [comment]
Glad it helped you out, you made my day!
